import {GoogleGenerativeAI} from "@google/generative-ai";
import {GeminiResponseType} from "../types/promptTypes.js";

// Initialize Gemini AI with the API key from environment variables
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!);


/**
 * Generates a response from the Gemini AI model based on the provided prompt text.
 *
 * @param {string} promptText - The formatted prompt text to send to the Gemini model.
 * @returns {Promise<GeminiResponseType>} A promise that resolves to an object containing:
 *   - text: The full response generated by the AI.
 *   - summary: A short summary (first 50 characters) of the response.
 *
 * @throws Will log and rethrow any errors encountered while communicating with the Gemini API.
 */
export const generateGeminiResponse = async (promptText: string): Promise<GeminiResponseType> => {
    try {
        const model = genAI.getGenerativeModel({model: "gemini-2.0-flash"});

        const result = await model.generateContent({
            contents: [
                {
                    role: "user",
                    parts: [{text: promptText}],
                },
            ],
        });

        const text = result.response.text();
        const summary = text.slice(0, 50);

        return {text, summary};
    } catch (error) {
        console.error("Gemini Error:", error);
        throw error;
    }
};
