name: Backend Checks
on:
  # Only trigger when a change happens in the '/backend' folder
  push:
    paths:
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"

jobs:
  pre-push:
    runs-on: ubuntu-latest
    # Run commands in the '/backend' folder
    defaults:
      run:
        working-directory: backend
    environment: Testing
    # Env is now available for all steps within the 'build' job
    env:
      HOME_REACT_ADDRESS: ${{secrets.HOME_REACT_ADDRESS}}
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      GEMINI_API_KEY: ${{secrets.GEMINI_API_KEY}}
      NODE_ENV: "test"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # Set up Yarn with Corepack
      - name: Enable Corepack and prepare Yarn
        run: |
          corepack enable
          yarn set version stable
      # Install dependencies
      - run: yarn install
      # Linting
      - run: yarn eslint . --ext .ts,.tsx --max-warnings 0 || exit 1
      # Type checking
      - run: yarn tsc --noEmit
      # Generate prisma and run tests
      - run: yarn prisma generate
      - run: yarn test
